<?php defined('ABSPATH') || exit; ?>

<div class="macp-card">
    <h2>CSS Exclusions</h2>
    
    <div class="macp-exclusions-container">
        <div class="macp-exclusion-section">
            <h3>CSS Class Safelist</h3>
            <p class="description">Classes listed here will never be removed from your CSS. One pattern per line. Use * for wildcards (e.g., slider-*).</p>
            
            <textarea name="macp_css_safelist" rows="5" class="large-text code"><?php 
                echo esc_textarea(implode("\n", get_option('macp_css_safelist', []))); 
            ?></textarea>
        </div>

        <div class="macp-exclusion-section">
            <h3>Excluded CSS Files</h3>
            <p class="description">CSS files containing these patterns will not be processed. One pattern per line.</p>
            
            <textarea name="macp_css_excluded_patterns" rows="5" class="large-text code"><?php 
                echo esc_textarea(implode("\n", get_option('macp_css_excluded_patterns', []))); 
            ?></textarea>
        </div>

        <div class="notice notice-info inline">
            <p>
                <strong>Tips:</strong>
                <ul>
                    <li>Use * for wildcard matching (e.g., slider-* will match all classes starting with "slider-")</li>
                    <li>Default WordPress classes are automatically preserved</li>
                    <li>Add dynamic classes generated by JavaScript here</li>
                    <li>Include third-party plugin classes that might not be detected</li>
                </ul>
            </p>
        </div>
    </div>
</div>